sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: cats
  redis:
    host: localhost
    port: 6379
    password: root
    database: 1
  wechat:
    appid: wxbce832a1710ef31c
    secret: 12522d1762f7b93fdc738950977004a3
